2021-01-26 07:54:41,183 INFO    MainThread:1580 [wandb_setup.py:_flush():70] setting env: {}
2021-01-26 07:54:41,184 INFO    MainThread:1580 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-26 07:54:41,184 INFO    MainThread:1580 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-26 07:54:41,184 INFO    MainThread:1580 [wandb_init.py:_log_setup():303] Logging user logs to /workspace/sts-lstm-siamese/wandb/run-20210126_075441-gnptt2nv/logs/debug.log
2021-01-26 07:54:41,184 INFO    MainThread:1580 [wandb_init.py:_log_setup():304] Logging internal logs to /workspace/sts-lstm-siamese/wandb/run-20210126_075441-gnptt2nv/logs/debug-internal.log
2021-01-26 07:54:42,083 INFO    MainThread:1580 [wandb_run.py:_console_start():1237] atexit reg
2021-01-26 07:54:42,083 INFO    MainThread:1580 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-26 07:54:42,083 INFO    MainThread:1580 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-26 07:54:42,083 INFO    MainThread:1580 [redirect.py:install():204] install start
2021-01-26 07:54:42,084 INFO    MainThread:1580 [redirect.py:install():219] install stop
2021-01-26 07:54:42,084 INFO    MainThread:1580 [redirect.py:install():204] install start
2021-01-26 07:54:42,084 INFO    MainThread:1580 [redirect.py:install():219] install stop
2021-01-26 07:54:42,084 INFO    MainThread:1580 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-26 07:54:47,348 INFO    MainThread:1580 [wandb_watch.py:watch():35] Watching
2021-01-26 07:54:52,351 INFO    MainThread:1580 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-26 07:54:52,352 INFO    MainThread:1580 [wandb_run.py:_restore():1179] restore
2021-01-26 07:54:52,352 INFO    MainThread:1580 [redirect.py:uninstall():223] uninstall start
2021-01-26 07:54:52,352 INFO    MainThread:1580 [redirect.py:_stop():278] _stop: stdout
2021-01-26 07:54:52,352 INFO    stdout    :1580 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-26 07:54:52,352 INFO    MainThread:1580 [redirect.py:_stop():284] _stop closed: stdout
2021-01-26 07:54:52,352 INFO    stdout    :1580 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:_stop():290] _stop joined: stdout
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:uninstall():227] uninstall done
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:uninstall():223] uninstall start
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:_stop():278] _stop: stderr
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:_stop():284] _stop closed: stderr
2021-01-26 07:54:52,353 INFO    stderr    :1580 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-26 07:54:52,353 INFO    stderr    :1580 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:_stop():290] _stop joined: stderr
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-26 07:54:52,353 INFO    MainThread:1580 [redirect.py:uninstall():227] uninstall done
2021-01-26 07:54:52,354 INFO    MainThread:1580 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "5322dcac215d43578b451936b27ca9ae"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 736
      total_bytes: 736
    }
  }
}

2021-01-26 07:54:54,360 INFO    MainThread:1580 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "24c3217737754d39928851540c15fabc"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3648
      total_bytes: 3648
    }
  }
}

2021-01-26 07:54:55,419 INFO    MainThread:1580 [wandb_run.py:_show_files():1536] logging synced files
2021-01-26 07:54:55,420 INFO    MainThread:1580 [internal.py:handle_exit():138] Internal process exited
