2021-01-26 07:33:51,577 INFO    MainThread:1309 [wandb_setup.py:_flush():70] setting env: {}
2021-01-26 07:33:51,577 INFO    MainThread:1309 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-26 07:33:51,577 INFO    MainThread:1309 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-26 07:33:51,577 INFO    MainThread:1309 [wandb_init.py:_log_setup():303] Logging user logs to /workspace/sts-lstm-siamese/wandb/run-20210126_073351-svcd8won/logs/debug.log
2021-01-26 07:33:51,577 INFO    MainThread:1309 [wandb_init.py:_log_setup():304] Logging internal logs to /workspace/sts-lstm-siamese/wandb/run-20210126_073351-svcd8won/logs/debug-internal.log
2021-01-26 07:33:52,512 INFO    MainThread:1309 [wandb_run.py:_console_start():1237] atexit reg
2021-01-26 07:33:52,513 INFO    MainThread:1309 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-26 07:33:52,513 INFO    MainThread:1309 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-26 07:33:52,513 INFO    MainThread:1309 [redirect.py:install():204] install start
2021-01-26 07:33:52,514 INFO    MainThread:1309 [redirect.py:install():219] install stop
2021-01-26 07:33:52,514 INFO    MainThread:1309 [redirect.py:install():204] install start
2021-01-26 07:33:52,514 INFO    MainThread:1309 [redirect.py:install():219] install stop
2021-01-26 07:33:52,514 INFO    MainThread:1309 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-26 07:33:57,819 INFO    MainThread:1309 [wandb_watch.py:watch():35] Watching
2021-01-26 07:34:02,847 INFO    MainThread:1309 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-26 07:34:02,847 INFO    MainThread:1309 [wandb_run.py:_restore():1179] restore
2021-01-26 07:34:02,847 INFO    MainThread:1309 [redirect.py:uninstall():223] uninstall start
2021-01-26 07:34:02,847 INFO    MainThread:1309 [redirect.py:_stop():278] _stop: stdout
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():284] _stop closed: stdout
2021-01-26 07:34:02,848 INFO    stdout    :1309 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-26 07:34:02,848 INFO    stdout    :1309 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():290] _stop joined: stdout
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:uninstall():227] uninstall done
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:uninstall():223] uninstall start
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():278] _stop: stderr
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():284] _stop closed: stderr
2021-01-26 07:34:02,848 INFO    stderr    :1309 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-26 07:34:02,848 INFO    stderr    :1309 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():290] _stop joined: stderr
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-26 07:34:02,848 INFO    MainThread:1309 [redirect.py:uninstall():227] uninstall done
2021-01-26 07:34:02,850 INFO    MainThread:1309 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "8eb0bc78d354494686f25c6968b62e63"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 736
      total_bytes: 736
    }
  }
}

2021-01-26 07:34:04,855 INFO    MainThread:1309 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "c82eb0634bd947f2b5a020971795df34"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3220
      total_bytes: 3220
    }
  }
}

2021-01-26 07:34:05,916 INFO    MainThread:1309 [wandb_run.py:_show_files():1536] logging synced files
2021-01-26 07:34:05,917 INFO    MainThread:1309 [internal.py:handle_exit():138] Internal process exited
