2021-01-26 15:55:20,880 INFO    MainThread:1906 [wandb_setup.py:_flush():70] setting env: {}
2021-01-26 15:55:20,880 INFO    MainThread:1906 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-26 15:55:20,880 INFO    MainThread:1906 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-26 15:55:20,880 INFO    MainThread:1906 [wandb_init.py:_log_setup():303] Logging user logs to /workspace/sts-lstm-siamese/wandb/run-20210126_155520-2gaehdka/logs/debug.log
2021-01-26 15:55:20,880 INFO    MainThread:1906 [wandb_init.py:_log_setup():304] Logging internal logs to /workspace/sts-lstm-siamese/wandb/run-20210126_155520-2gaehdka/logs/debug-internal.log
2021-01-26 15:55:21,770 INFO    MainThread:1906 [wandb_run.py:_console_start():1237] atexit reg
2021-01-26 15:55:21,771 INFO    MainThread:1906 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-26 15:55:21,771 INFO    MainThread:1906 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-26 15:55:21,771 INFO    MainThread:1906 [redirect.py:install():204] install start
2021-01-26 15:55:21,771 INFO    MainThread:1906 [redirect.py:install():219] install stop
2021-01-26 15:55:21,771 INFO    MainThread:1906 [redirect.py:install():204] install start
2021-01-26 15:55:21,773 INFO    MainThread:1906 [redirect.py:install():219] install stop
2021-01-26 15:55:21,773 INFO    MainThread:1906 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-26 15:55:27,056 INFO    MainThread:1906 [wandb_watch.py:watch():35] Watching
2021-01-26 15:55:32,122 INFO    MainThread:1906 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-26 15:55:32,122 INFO    MainThread:1906 [wandb_run.py:_restore():1179] restore
2021-01-26 15:55:32,122 INFO    MainThread:1906 [redirect.py:uninstall():223] uninstall start
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():278] _stop: stdout
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():284] _stop closed: stdout
2021-01-26 15:55:32,123 INFO    stdout    :1906 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-26 15:55:32,123 INFO    stdout    :1906 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():290] _stop joined: stdout
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:uninstall():227] uninstall done
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:uninstall():223] uninstall start
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():278] _stop: stderr
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():284] _stop closed: stderr
2021-01-26 15:55:32,123 INFO    stderr    :1906 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-26 15:55:32,123 INFO    stderr    :1906 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():290] _stop joined: stderr
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-26 15:55:32,123 INFO    MainThread:1906 [redirect.py:uninstall():227] uninstall done
2021-01-26 15:55:32,125 INFO    MainThread:1906 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "5fa1273ff0254f359a0faa7e742a5d56"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 736
      total_bytes: 736
    }
  }
}

2021-01-26 15:55:34,130 INFO    MainThread:1906 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "17076ebbcb9849f29c52f92d91676aa3"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3853
      total_bytes: 3853
    }
  }
}

2021-01-26 15:55:35,190 INFO    MainThread:1906 [wandb_run.py:_show_files():1536] logging synced files
2021-01-26 15:55:35,191 INFO    MainThread:1906 [internal.py:handle_exit():138] Internal process exited
